### ISSUE TITLE
Add rust-toolchain.toml

### ISSUE THREAD

**Issue by peter-lyons-kehl** [CIRCLECI-GWP/rust-api-heroku#1]
Hi Oluyemi @yemiwebby or friend,

`RustConfig` seems to be Herok-specific. It's not used by Rust at all. (See https://github.com/peter-lyons-kehl/try_rustconfig for minimization.)

Suggest adding a file `rust-toolchain.toml` containing:
```toml
[toolchain]
channel = "nightly"
```
